import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'Ahad-Chat-App',
    src: 'ahadapp.png',
    color: '#dbeafe',
    url: 'https://ahad-chat-app.vercel.app/login',
    role: 'Fullstack Developer',
  },
  {
    title: 'Chit-chat-App',
    src: 'chitchat.png',
    color: '#ddd6fe',
    url: 'https://chit-chat-sable.vercel.app/',
    role: 'Fullstack Developer',
  },
  {
    title: 'E-Grocery',
    src: 'egrocery.png',
    color: '#fae8ff',
    url: 'https://e-grocery-eight.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Grocy-Mart',
    src: 'grocymart.png',
    color: '#fee2e2',
    url: 'https://grocy-mart.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Crypto-Dashboard',
    src: 'crypto.png',
    color: '#dbeafe',
    url: 'https://crypto-dashboard-mocha-pi.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Hospital-Admin Dashboard',
    src: 'hospital-admin.png',
    color: '#ddd6fe',
    url: 'https://hospitap-admin-dashboard.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: '2048game',
    src: '2048.png',
    color: '#ffedd5',
    url: 'https://2048-game-sand.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Snakegame',
    src: 'snake.png',
    color: '#ecfccb',
    url: 'https://snake-game-eta-blond.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Quizgame',
    src: 'quiz-app.png',
    color: '#ecfccb',
    url: 'https://snake-game-eta-blond.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Netflix-clone',
    src: 'netflix-clone.png',
    color: '#ecfccb',
    url: 'https://snake-game-eta-blond.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Admin-Dashbaord',
    src: 'admin-dashboard.png',
    color: '#ecfccb',
    url: 'https://snake-game-eta-blond.vercel.app/',
    role: 'Frontend Developer',
  },
  {
    title: 'Restaurant-App',
    src: 'restaurant.png',
    color: '#ecfccb',
    url: 'https://snake-game-eta-blond.vercel.app/',
    role: 'Frontend Developer',
  },
];
